"""Stage-4 validation cases: widen the coverage gaps documented in README.md's "Limits of that evidence" section
(generated by tools/make_cases_ext.py, references by tools/run_fortran_cases.sh, same machinery as test_cases.py).

- ``cc01`` (NH4HSO4 alone, 18 points): activates the Qcca/Rcc three-ion interaction terms in mr.py, previously
  ported but untested -- Fortran's own comment on the underlying tables says they are "so far only used for
  [NH4+|H+|HSO4-] containing mixtures" (ModMRpart.f90). NH4HSO4 dissociates (HSO4- <-> H+ + SO4--), so a single
  salt is enough to bring NH4+, H+ and HSO4- into simultaneous, nonzero molality.
- ``cc02``/``cc03``/``cc04`` (ethyl acetate / dimethyl ether / acetic acid, each + NaCl, 10 points): the ester
  (CH3COO), ether (CH3O) and carboxylic-acid (COOH) main groups, not exercised by any case in test_cases.py
  (which only uses alcohols and acetone for its organic components).
- ``cc05``/``cc06`` (toluene / methylamine + water only, no salt, 16 points each): the aromatic-ring (AC/ACH) and
  amine (CH3NH2) main groups. Both are electrolyte-free by necessity, not choice: AIOMFAC's MR main-group<->ion
  parameter tables have no entries for either main group with any cation (Fortran errorflagmix 1) -- confirmed
  directly against the Python port, which raises ValueError for e.g. toluene+NaCl. That is a genuine limit of
  what the (electrolyte-containing) AIOMFAC parameterization covers, not a porting gap.
- ``cc07``/``cc08`` (PEG oligomer + water; PEG oligomer + (NH4)2SO4, 16 / 10 points): subgroup 154
  (CH2OCH2[PEG], main group 70) and the ``isPEGsystem`` special-case parameters it triggers (system.py:
  overrides R/Q of subgroup 154 itself in the SR combinatorial term, replacing the tabulated Bondi (1964)
  values; mr.py: overrides the CHn[OH,PEG] main group (52/68) <-> NH4+/SO4-- MR interaction coefficients).
  cc08 additionally confirms the MR override actually changes a value rather than being a no-op (see
  ``test_peg_mr_override_actually_changes_a_value``).

All reference inputs carry an explicit "smiles-based pure-component method? 0" (armeliON = .false.) so the
Fortran run doesn't need the separately-licensed TgML_Armeli viscosity/Tg machine-learning lookup (not installed
here, and irrelevant to activity coefficients -- verified to produce a byte-identical debug_terms.txt with/without
it for an existing case, since armeliON only feeds PureCompViscosity).
"""
import numpy as np
import pytest

from aiomfac_py import ActivityModel, read_input_file
from reference_utils import REF, parse_dump, parse_output_table

CASES = {
    "cc01": "NH4HSO4 (Qcca/Rcc three-ion interaction terms)",
    "cc02": "ethyl acetate + NaCl (ester main group)",
    "cc03": "dimethyl ether + NaCl (ether main group)",
    "cc04": "acetic acid + NaCl (carboxylic-acid main group)",
    "cc05": "toluene + water, electrolyte-free (aromatic-ring main group)",
    "cc06": "methylamine + water, electrolyte-free (amine main group)",
    "cc07": "PEG oligomer + water, electrolyte-free (subgroup 154 R/Q override)",
    "cc08": "PEG oligomer + (NH4)2SO4 (subgroup 154 R/Q override + MR CHn[OH,PEG]<->NH4+/SO4-- override)",
}
TOL = 1e-12


def _scaled(a, b):
    a, b = np.asarray(a), np.asarray(b)
    assert a.shape == b.shape, (a.shape, b.shape)
    if a.size == 0:
        return 0.0
    return float(np.max(np.abs(a - b) / np.maximum(1.0, np.abs(b))))


def _load(n):
    d = REF / "ext"
    case = read_input_file(d / "inputs" / f"input_{n}.txt")
    pts = parse_dump(d / "dumps" / f"debug_terms_{n}.txt.gz")
    out = parse_output_table(d / "outputs" / f"AIOMFAC_output_{n}.txt")
    return case, pts, out


@pytest.mark.parametrize("n", CASES)
def test_case_every_stage_matches_fortran(n):
    case, pts, _ = _load(n)
    assert len(pts) == case.npoints
    model = ActivityModel(case.components)
    for k, p in enumerate(pts):
        r = model.evaluate(case.fractions[k], case.T_K[k], case.basis)
        nn, nc, na = p["dims"]
        assert (model.mixture.n_neutral, model.mixture.n_cation, model.mixture.n_anion) == (nn, nc, na)
        stages = {
            "mass fractions": (r.wtf, p["wtf"]), "X": (r.x, p["X"]), "XN": (r.xn, p["XN"][:nn]),
            "cation molalities": (r.smc[:nc], p["SMC"]), "anion molalities": (r.sma[:na], p["SMA"]),
            "LR": (r.ln_gamma_lr, np.concatenate([p["gnlrln"], p["gclrln"], p["galrln"]])),
            "MR": (r.ln_gamma_mr, np.concatenate([p["gnmrln"], p["gcmrln"], p["gamrln"]])),
            "SR": (r.ln_gamma_sr, np.concatenate([p["gnsrln"], p["gcsrln"], p["gasrln"]])),
            "ln gamma": (r.ln_gamma, np.concatenate([p["lnactcoeff_n"], p["lnactcoeff_c"], p["lnactcoeff_a"]])),
            "gamma neutrals": (r.gamma_neutral, p["actcoeff_n"]),
            "activities": (r.activity, p["activity"]),
        }
        for name, (a, b) in stages.items():
            assert _scaled(a, b) < TOL, f"case {n} point {k + 1}: {name}"


@pytest.mark.parametrize("n", CASES)
def test_case_matches_printed_fortran_output(n):
    """independent of the instrumentation: the unmodified Fortran output routine prints a_coeff_x with 6 digits"""
    case, _, out = _load(n)
    model = ActivityModel(case.components)
    nn = model.mixture.n_neutral
    for k in range(case.npoints):
        r = model.evaluate(case.fractions[k], case.T_K[k], case.basis)
        for cp in range(1, nn + 1):
            if r.gamma_neutral[cp - 1] > 0.0:
                assert out[cp][k, 5] == pytest.approx(r.gamma_neutral[cp - 1], rel=5e-6), (n, k + 1, cp)


def test_fortran_flags_are_clean():
    for n in CASES:
        _, _, out = _load(n)
        flags = set(np.concatenate([rows[:, 7] for rows in out.values()]).astype(int).tolist())
        assert flags == {0}, (n, flags)


def test_qcca_and_rcc_actually_activate_for_cc01():
    """guards against cc01 silently exercising the untested code path's *absence* -- confirms NH4+, H+ and
    HSO4- are all simultaneously present (so mr.py's QccaInteract/RccInteract are True) and that at least one
    point has a nonzero net contribution from the Qcca/Rcc terms."""
    case, _, _ = _load("cc01")
    model = ActivityModel(case.components)
    assert set(model.mixture.sr.cations) >= {204, 205}          # NH4+, H+
    assert 248 in model.mixture.sr.anions                       # HSO4-
    assert model._mr.QccaInteract and model._mr.RccInteract
    r = model.evaluate(case.fractions[-1], case.T_K[-1], case.basis)   # most concentrated point
    assert np.all(np.isfinite(r.ln_gamma))


def test_peg_sr_and_mr_overrides_actually_change_a_value():
    """guards against cc07/cc08 silently exercising the *absence* of the isPEGsystem special-case code (i.e.
    against a bug that made ``is_peg_system`` never fire). The SR override (system.py: R/Q of subgroup 154)
    turns out to be a no-op against the *current* parameter tables -- the tabulated Bondi values for subgroup
    154 already equal 1.38143/3.0, the same numbers ModSRunifac.f90 additionally hardcodes in its isPEGsystem
    branch (a redundant safety net, not a live override) -- so it's confirmed by exact-value equality here
    instead of by inequality. The MR override (mr.py: CHn[OH,PEG]<->NH4+/SO4--) is a real override: confirmed
    by comparing cc08 against an otherwise-identical non-PEG system with the same OH main group."""
    from aiomfac_py import Component
    from aiomfac_py.params import load_sr_params
    from aiomfac_py.system import _PEG_Q, _PEG_R

    case = _load("cc07")[0]
    model = ActivityModel(case.components)
    assert model.mixture.sr.is_peg_system
    sp = load_sr_params()
    col154 = model.mixture.sr.solv_subs.index(154)
    assert model.mixture.sr.R[col154] == pytest.approx(_PEG_R)
    assert model.mixture.sr.R[col154] == pytest.approx(sp.R[153], rel=1e-5)   # table is single-precision-derived
    assert model.mixture.sr.Q[col154] == pytest.approx(_PEG_Q) == pytest.approx(sp.Q[153])

    case8 = _load("cc08")[0]
    peg_model = ActivityModel(case8.components)
    water = Component(1, "Water", ((16, 1),))
    alc = Component(2, "x_alc", ((150, 2), (153, 2)))            # same OH main group (68), no subgroup 154
    nh4so4 = Component(3, "x_AS", ((204, 2), (261, 1)))
    control_model = ActivityModel([water, alc, nh4so4])
    assert peg_model.mixture.sr.is_peg_system and not control_model.mixture.sr.is_peg_system
    row68_peg = peg_model.mixture.imaingroup.index(68)
    row68_ctrl = control_model.mixture.imaingroup.index(68)
    assert peg_model._mr.bnc[row68_peg, 0] != pytest.approx(control_model._mr.bnc[row68_ctrl, 0])
    assert peg_model._mr.bnc[row68_peg, 0] == pytest.approx(3.0576783e-01)


def test_aromatic_and_amine_main_groups_have_no_electrolyte_mr_parameters():
    """documents the *reason* cc05/cc06 are electrolyte-free: not a porting gap, a real limit of AIOMFAC's MR
    parameterization (Fortran errorflagmix 1 -- no main-group<->ion parameters defined for AC/ACH or CH3NH2)."""
    from aiomfac_py import Component

    water = Component(1, "Water", ((16, 1),))
    nacl = Component(3, "NaCl", ((202, 1), (242, 1)))
    toluene = Component(2, "Toluene", ((9, 5), (11, 1)))
    methylamine = Component(2, "Methylamine", ((28, 1),))
    for organic in (toluene, methylamine):
        with pytest.raises(ValueError, match="not defined"):
            ActivityModel([water, organic, nacl])
