"""Stage-3 validation cases: the complete pipeline against the instrumented Fortran model on 9 additional mixtures
(145 composition points; generated by tools/make_cases.py, references by tools/run_fortran_cases.sh)."""
import numpy as np
import pytest

from aiomfac_py import ActivityModel, read_input_file
from reference_utils import REF, parse_dump, parse_output_table

CASES = {
    "0101": "NaCl, dilute -> near saturation",
    "0102": "CaCl2 (divalent cation)",
    "0103": "MgCl2 (divalent cation)",
    "0104": "LiCl (high ionic strength)",
    "0105": "NaCl + KBr (cross-combination electrolytes NaBr, KCl)",
    "0106": "water + ethanol + NaCl (organic and salt vary independently, mole fractions)",
    "0107": "4 organics + CaCl2, temperature sweep 275-325 K",
    "0108": "random: 1-propanol + NaNO3 + NH4Cl + MgCl2 + KNO3 (4 cations, 2 anions, 8 electrolyte components)",
    "0109": "dilute limit and zero-abundance components",
}
TOL = 1e-12          # scaled difference; observed agreement is <= 7e-15


def _scaled(a, b):
    a, b = np.asarray(a), np.asarray(b)
    assert a.shape == b.shape, (a.shape, b.shape)
    return float(np.max(np.abs(a - b) / np.maximum(1.0, np.abs(b))))


def _load(n):
    d = REF / "cases"
    case = read_input_file(d / "inputs" / f"input_{n}.txt")
    pts = parse_dump(d / "debug_terms" / f"debug_terms_{n}.txt.gz")
    out = parse_output_table(d / "outputs" / f"AIOMFAC_output_{n}.txt")
    return case, pts, out


@pytest.mark.parametrize("n", CASES)
def test_case_every_stage_matches_fortran(n):
    case, pts, _ = _load(n)
    assert len(pts) == case.npoints
    model = ActivityModel(case.components)
    for k, p in enumerate(pts):
        r = model.evaluate(case.fractions[k], case.T_K[k], case.basis)
        nn, nc, na = p["dims"]
        assert (model.mixture.n_neutral, model.mixture.n_cation, model.mixture.n_anion) == (nn, nc, na)
        stages = {
            "mass fractions": (r.wtf, p["wtf"]), "X": (r.x, p["X"]), "XN": (r.xn, p["XN"][:nn]),
            "cation molalities": (r.smc[:nc], p["SMC"]), "anion molalities": (r.sma[:na], p["SMA"]),
            "LR": (r.ln_gamma_lr, np.concatenate([p["gnlrln"], p["gclrln"], p["galrln"]])),
            "MR": (r.ln_gamma_mr, np.concatenate([p["gnmrln"], p["gcmrln"], p["gamrln"]])),
            "SR": (r.ln_gamma_sr, np.concatenate([p["gnsrln"], p["gcsrln"], p["gasrln"]])),
            "ln gamma": (r.ln_gamma, np.concatenate([p["lnactcoeff_n"], p["lnactcoeff_c"], p["lnactcoeff_a"]])),
            "gamma neutrals": (r.gamma_neutral, p["actcoeff_n"]),
            "activities": (r.activity, p["activity"]),
        }
        for name, (a, b) in stages.items():
            assert _scaled(a, b) < TOL, f"case {n} point {k + 1}: {name}"


@pytest.mark.parametrize("n", CASES)
def test_case_matches_printed_fortran_output(n):
    """independent of the instrumentation: the unmodified Fortran output routine prints a_coeff_x with 6 digits"""
    case, _, out = _load(n)
    model = ActivityModel(case.components)
    nn = model.mixture.n_neutral
    for k in range(case.npoints):
        r = model.evaluate(case.fractions[k], case.T_K[k], case.basis)
        for cp in range(1, nn + 1):
            if r.gamma_neutral[cp - 1] > 0.0:
                assert out[cp][k, 5] == pytest.approx(r.gamma_neutral[cp - 1], rel=5e-6), (n, k + 1, cp)


def test_fortran_flags_are_clean_except_expected_temperature_warning():
    """all reference runs finished without errors; the only non-zero per-point flag is warning 10 (T outside 288-309 K
    for electrolyte mixtures), which is expected for the temperature sweeps 0107/0108."""
    for n in CASES:
        _, _, out = _load(n)
        flags = set(np.concatenate([rows[:, 7] for rows in out.values()]).astype(int).tolist())
        assert flags <= {0, 10}, (n, flags)
        if n not in ("0107", "0108"):
            assert flags == {0}, (n, flags)


def test_coverage_of_the_new_cases():
    """documents what the cases exercise (guards against silently shrinking the validation set)"""
    imax, imin, tmin, tmax, npts = 0.0, 1e9, 1e9, 0.0, 0
    for n in CASES:
        case, _, _ = _load(n)
        model = ActivityModel(case.components)
        for k in range(case.npoints):
            r = model.evaluate(case.fractions[k], case.T_K[k], case.basis)
            if r.ionic_strength > 0:
                imax, imin = max(imax, r.ionic_strength), min(imin, r.ionic_strength)
            tmin, tmax = min(tmin, case.T_K[k]), max(tmax, case.T_K[k])
            npts += 1
    assert npts == 145
    assert imax > 8.0 and imin < 1e-6                 # ionic strength spans > 7 orders of magnitude (mol/kg)
    assert tmin <= 275.0 and tmax >= 325.0
